description: >
  Update Release status in issues
parameters:
  path:
    description: >
      scripts destination path
    type: env_var_name
    default: RELEASE_SCRIPTS_PATH
  issues_file:
    description: >
      file containing issues created with the command load issues
    type: env_var_name
    default: ISSUES_FILE
  version_file:
    description: >
      File containing release version
    type: env_var_name
    default: VERSION_FILE
  github_token:
    description: >
      Github Api token
    type: env_var_name
    default: GITHUB_TOKEN
  flavor:
    description: >
      Nunav flavor
    type: env_var_name
    default: FLAVOR
steps:
  - run:
      name: Load issues
      command: ./${!SCRIPT_PATH}/update_issue_deployment_status_comment.sh issues_file="${!ISSUES}" version_file="${!VERSION}" github_token="${!TOKEN}" github_repository="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" flavor="${!APP_FLAVOR}"
      environment:
        SCRIPT_PATH: <<parameters.path>>
        ISSUES: <<parameters.issues_file>>
        VERSION: <<parameters.version_file>>
        TOKEN: <<parameters.github_token>>
        APP_FLAVOR: <<parameters.flavor>>
