description: >
  Update Release status in issues
parameters:
  issues_file:
    description: >
      file containing issues created with the command load issues
    type: env_var_name
    default: ISSUES_FILE
  version_file:
    description: >
      File containing release version
    type: env_var_name
    default: VERSION_FILE
  github_token:
    description: >
      Github Api token
    type: env_var_name
    default: GITHUB_TOKEN
  flavor:
    description: >
      Nunav flavor
    type: env_var_name
    default: FLAVOR
  extra_steps:
    description: >
      Extra steps that will run at the beginning of the command
    type: steps
    default: []
steps:
  - steps: << parameters.extra_steps >>
  - run:
      name: Load issues
      command: <<include(scripts/update_issue_deployment_status_comment.sh)>>
      environment:
        ISSUES: <<parameters.issues_file>>
        VERSION: <<parameters.version_file>>
        TOKEN: <<parameters.github_token>>
        APP_FLAVOR: <<parameters.flavor>>
