name: test worflow

on:
  workflow_call:
    inputs:
      parameter:
        required: true
        type: string
        
jobs:
  echo-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: print text
        run: echo ${{inputs.parameter}}
  
